version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:   
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crudapi
      MYSQL_USER: gustavo
      MYSQL_PASSWORD: apiportfolio
      MYSQL_ROOT_PASSWORD: apiportfolio
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
