services:
  - type: web
    name: server
    env: docker
    buildCommand: "docker build -t gestaofuncionarios ."
    startCommand: "docker run -d -p 8080:8080 gestaofuncionarios"
    dockerfilePath: "Gustav-dev97/JavaAPI_REST-SpringBoot-Hibernate/blob/main/GustavoGerenciaFuncionarios/Dockerfile"
    envVars:
      - key: PORT
        value: 8080
    dependsOn:
      - mysqldb

  - type: pserv
    name: mysqldb
    env: docker
    image: "mysql:5.7"
    envVars:
      - key: MYSQL_DATABASE
        value: crudapi
      - key: MYSQL_USER
        value: gustavo
      - key: MYSQL_PASSWORD
        value: apiportfolio
      - key: MYSQL_ROOT_PASSWORD
        value: apiportfolio
    volumes:
      - source: init-db
        mountPath: /docker-entrypoint-initdb.d

volumes:
  - name: init-db
    path: "./init-db.sql"
